hmrc/ated-frontend

app/views/editLiability/editLiabilitySummary.scala.html
=> ATED-3567 Styling to edit liability page fixed

app/views/editLiability/editLiabilitySummary.scala.html
=> ATED-3573 change to id

app/views/editLiability/hasBankDetails.scala.html, test/views/editLiability/hasBankDetailsSpec.scala
=> ATED-3574 same nae for attribute on radio inputs

public/stylesheets/main.css
=> ATED-3576 change to the error message colour

conf/messages, test/controllers/AccountSummaryControllerSpec.scala
=> ATED-3577 Changes from the walkthrough

app/views/propertyDetails/chargeableReturnsConfirmation.scala.html, app/views/propertyDetails/propertyDetailsSummary.scala.html, app/views/reliefs/reliefsSent.scala.html, app/views/reliefs/reliefsSummary.scala.html, conf/messages
=> ATED-3578 Changes from the walkthrough

app/config/ApplicationGlobal.scala, app/controllers/auth/AtedGovernmentGateway.scala, app/controllers/auth/ExternalUrls.scala, conf/application.conf, project/FrontendBuild.scala
also fixed grafana metrics config
=> added another setting for session timeout

app/views/periodSummary.scala.html, public/stylesheets/main.css, test/views/periodSummarySpec.scala
=> ATED-3579 change from a table to a div

app/views/propertyDetails/propertyDetailsSummary.scala.html, test/views/propertyDetails/propertyDetailsSummarySpec.scala
=> ATED-3619 Changed ATED charge to be a sentence

app/views/editLiability/editLiabilitySent.scala.html
=> ATED 3623 Took tick off page

app/views/editLiability/disposeLiabilitySummary.scala.html
=> ATED-3714 changes to edit ids

README.md
/pull/11/files#diff-04c6e90faac2675aa89e2176d2eec7d8
=> ATED-3689: minor change in README

app/views/propertyDetails/periodsInAndOutRelief.scala.html, public/stylesheets/main.css
=> ATED-3795: Removed heading class, removed aria-labels.

conf/messages
Taken off the p tags on the messages file
=> ATED-3881 Taken off the p tags on the messages file

app/views/editLiability/editLiabilityDatesLiable.scala.html, app/views/propertyDetails/periodDatesLiable.scala.html, app/views/propertyDetails/periodInReliefDates.scala.html, test/views/propertyDetails/periodDatesLiableSpec.scala, test/views/propertyDetails/periodInReliefDatesSpec.scala
=> ATED-3910 CHANGE CONTENT IN BUTTON

app/views/propertyDetails/propertyDetailsAddress.scala.html, test/views/propertyDetails/PropertyDetailsAddressSpec.scala
=> ATED-3929: Fix enter address page.

app/views/formBundleReturn.scala.html, conf/messages, public/stylesheets/main.css, test/views/formBundleReturnSpec.scala
=> ATED-3927: Fix HTML issues, small content tweaks.

app/views/editLiability/editLiability.scala.html, conf/messages, test/controllers/editLiability/EditLiabilityTypeControllerSpec.scala, test/views/editLiability/editLiabilitySpec.scala
=> ATED-3928: Update Edit your ATED return page.

app/views/editLiability/dataOfDisposal.scala.html, app/views/helpers/atedDateFieldsFree.scala.html, app/views/helpers/atedInputNew.scala.html
=> ATED-3932: Fix dispose property page.

app/views/editLiability/disposeLiabilityHasBankDetails.scala.html, conf/messages, test/controllers/editLiability/DisposeLiabilityHasBankDetailsControllerSpec.scala, test/controllers/editLiability/HasBankDetailsControllerSpec.scala, test/views/editLiability/disposeLiabilityHasBankDetailsSpec.scala, test/views/editLiability/hasBankDetailsSpec.scala
=> ATED-3933: Fix has bank account page.

app/views/propertyDetails/propertyDetailsAcquisition.scala.html, conf/messages, test/controllers/propertyDetails/PropertyDetailsAcquisitionControllerSpec.scala
I have done the content on the page but not the testing due to the error I'm getting on my machine. I have changed the page back apart from moving the show/hide reveal and made sure the link is correct this was told to be done by steven
=> ATED-3793 acquisiton page changed back

app/config/ApplicationConfig.scala, conf/application.conf
Updated the contact-frontend details to fix the get help with this page link
=> ATED-3855: contact-frontend updates

app/controllers/editLiability/EditLiabilitySentController.scala, app/views/editLiability/disposeLiabilitySent.scala.html, app/views/editLiability/editLiabilitySent.scala.html, app/views/editLiability/editLiabilitySentPrintFriendly.scala.html, app/views/propertyDetails/chargeableConfirmationPrintFriendly.scala.html, conf/messages, test/controllers/editLiability/EditLiabilitySentControllerSpec.scala
=> ATED-3946: Update liability edit sent page.

app/views/editLiability/bankDetails.scala.html, app/views/editLiability/disposeLiabilityBankDetails.scala.html, app/views/propertyDetails/propertyDetailsNewBuild.scala.html, conf/messages, public/javascript/bankDetails.js, test/controllers/editLiability/BankDetailsControllerSpec.scala, test/controllers/editLiability/DisposeLiabilityBankDetailsControllerSpec.scala, test/views/editLiability/bankDetailsSpec.scala, test/views/editLiability/disposeLiabilityBankDetailsSpec.scala
=> Ated 3882: Add progressive reveal to bank details page.

app/views/editLiability/editLiability.scala.html, app/views/propertyDetails/propertyDetailsNewBuild.scala.html, app/views/propertyDetails/propertyDetailsOwnedBefore.scala.html, app/views/propertyDetails/propertyDetailsTaxAvoidance.scala.html, conf/messages, test/utils/AtedUtilsSpec.scala, test/views/subscriptionData/CompanyDetailsSpec.scala
=> Ated 3952 - Updates Journey 5

conf/messages
=> updated land reg uri

test/controllers/SelectPeriodControllerSpec.scala
DDCNLS-2730: Updated unit tests for year 2017
=> DDCNLS-2730: Updated unit tests for year 2017

app/views/_accountSummary_sideBar.scala.html, app/views/editLiability/disposeLiabilityPrintFriendly.scala.html, app/views/editLiability/editLiabilityPrintFriendly.scala.html, app/views/main.scala.html, app/views/propertyDetails/propertyDetailsPrintFriendly.scala.html, app/views/reliefs/reliefsPrintFriendly.scala.html, conf/messages
Hardcoding removed and unit tests are okay.
=> DDCNLS-2953: Remove hardcoding

app/views/helpers/fullWidthBanner.scala.html, app/views/main.scala.html, public/stylesheets/urBanner.css
=> beta banner removed and ur banner style updated

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, conf/application-json-logger.xml
Updating with standard DDCTLS checklists and amending to correct level of logging for ated-frontend
=> DL-1899 Add checklists and amend json-logger

conf/application.conf
DL-2214 - update GA config
**Maintenance** 
Updating config to standard implementation as config should be done within app-config for relevant environments
=> DL-2214 update GA config

app/controllers/auth/AuthAction.scala, test/controllers/auth/AuthActionSpec.scala
DL-2269b - redirection Url amend
**Bug fix** 
Redirection URL amended 
=> DL-2269b amend expected routing for redirect url

app/controllers/auth/ClientHelper.scala, app/services/DelegationService.scala
Changed no Delegation message from warn to info
Iyke
=> Changed no Delegation message from warn to info

app/models/StandardAuthRetrievals.scala
**Monitoring**
So as to correctly assess some behaviour in production, added a log to inform us whether or not the behaviour is "correct"
=> Added log to see how many ATED refs someone has

app/models/StandardAuthRetrievals.scala
=> LoggersAdded - additional loggers added

app/controllers/auth/ClientHelper.scala, app/models/StandardAuthRetrievals.scala
=> Added more logging and changed comparison for agents

app/models/StandardAuthRetrievals.scala
AgentAuthLinkChange
**Bug fix** 
Fix issues whereby Agent acting on behalf of client were not being stored and user experiencing Internal Server Error exceptions
=> AgentAuthLionkChange fix issues with agents acting on clients behalf

app/connectors/AtedConnector.scala, app/connectors/PropertyDetailsConnector.scala, app/services/PropertyDetailsService.scala, app/services/ReliefsService.scala
**Bug fix
Connector routing to backend 
- x ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
=> reliefsAndLiablityFixes - Fixing route issues with connectors

app/views/formBundleReturn.scala.html, project/FrontendBuild.scala
**Bug fix** (delete as appropriate)
Html arranged correctly 
-  [x]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
- []  I've executed the acceptance test pack locally to ensure there are no functional regressions
=> Dl 2174 - Bug fix for return status

app/views/formBundleReturn.scala.html
**Bug fix ** (delete as appropriate)
- []  I've executed the acceptance test pack locally to ensure there are no functional regressions
=> DL-2174 - Bug Fix for return status

app/models/ReliefModels.scala, app/services/ReliefsService.scala, app/utils/ReliefsUtils.scala, test/builders/ReliefBuilder.scala, test/controllers/reliefs/AvoidanceSchemesControllerSpec.scala
**Bug fix** (delete as appropriate)
Due to code changes implemented on backend for DL-2437 we have had to amend frontend to accommodate the changes to SaveDraftReliefs. This will work in conjunction with ated be 3.31.0
=> DL-2437 Added atedRefNo to relief model

app/views/unauthorised.scala.html
**Bug fix** 
Adding Get help with this page link identified during environment checks in QA
=> DL-2333getHelp adding Get help with this page

app/controllers/reliefs/ReliefsSentController.scala, app/views/reliefs/reliefsSent.scala.html, app/views/reliefs/reliefsSentPrintFriendly.scala.html, conf/app.routes, conf/logback-test.xml, conf/messages, project/FrontendBuild.scala, project/MicroService.scala, test/controllers/reliefs/ReliefsSentControllerSpec.scala, test/views/reliefs/ReliefsSentPrintFriendlySpec.scala, test/views/reliefs/ReliefsSentSpec.scala
*New feature**
Show additional text on relief return confirmation and printer friendly version to inform the user how the report change in circumstances.
*Reviewee* (David Thornton)
*Reviewer* (Replace with your Paul Anderson)
=> DL-2764: Added change of circumstance content to relief return confirmation

conf/messages
=> DL-2698 - content change for 60 days draft saving logic

app/controllers/propertyDetails/ConfirmAddressController.scala, app/controllers/propertyDetails/PropertyDetailsAddressController.scala, app/controllers/propertyDetails/SelectExistingReturnAddressController.scala, app/utils/AtedUtils.scala, app/views/propertyDetails/propertyDetailsAddress.scala.html, conf/messages, project/FrontendBuild.scala, test/controllers/propertyDetails/ConfirmAddressControllerSpec.scala, test/controllers/propertyDetails/PropertyDetailsAddressControllerSpec.scala
Back Link Bug for DL-2824
**Bug fix** 
*Reviewee* (Iyke)
=> DL-2824 - BackLinkBug fix

conf/messages, public/stylesheets/_checkAnswers.css, test/views/html/AccountSummarySpec.scala
=> DL-2769-2: Changed Currently showing to Showing and added unit tests

app/controllers/PeriodSummaryController.scala, app/controllers/PrevPeriodsSummaryController.scala, app/controllers/SelectPeriodController.scala, app/views/_accountSummary_sideBar.scala.html, app/views/accountSummary.scala.html, app/views/prevPeriodsSummary.scala.html, app/views/propertyDetails/propertyDetailsSummary.scala.html, conf/app.routes, conf/messages, test/controllers/PrevPeriodsSummaryControllerSpec.scala, test/utils/TestModels.scala, test/views/html/AccountSummarySidebarSpec.scala, test/views/html/AccountSummarySpec.scala, test/views/html/PrevPeriodsSummarySpec.scala
**New feature**
* Split the previous returns into another page, accessible for the side bar
=> DL-2776 - Previous Summary page added and tested, Side Link changed

app/controllers/SelectPeriodController.scala, test/controllers/SelectPeriodControllerSpec.scala
**Bug fix**
* Fixed future periods displaying if no period is selected
=> DL-2854 Fixed future period bug

conf/messages
=> DL-2674 - Content change for typo

app/controllers/AccountSummaryController.scala, app/controllers/PeriodSummaryController.scala, app/views/accountSummary.scala.html, app/views/periodSummary.scala.html, app/views/periodSummaryPastReturns.scala.html, conf/app.routes, test/controllers/PeriodSummaryControllerSpec.scala, test/views/html/AccountSummarySpec.scala
**Bug fix **
Backlink Bug fix change for return-type page
=> DL-2883 - Backlink fix for return-type page

app/controllers/subscriptionData/CorrespondenceAddressController.scala, project/FrontendBuild.scala, project/plugins.sbt, test/controllers/subscriptionData/CorrespondenceAddressControllerSpec.scala
DL-2891 New error message for correspondence address page
**Bug fix**
Error message for users who are unable to update their address due to ETMP unavailability
*Iyke*
=> DL-2891 New error message for correspondence address page

app/views/main.scala.html, project/FrontendBuild.scala, project/MicroService.scala, test/views/html/AccountSummarySpec.scala
**Change**
* Altered link of main heading. This will go to the client summary for agents and the ATED summary for a client.
=> DL-2916 Altered link of main heading

conf/messages, test/views/propertyDetails/propertyDetailsSummarySpec.scala, test/views/reliefs/ReliefsSummarySpec.scala
**Bug fix**
* Fixed misleading content on summary pages.
=> DL-2919 Fixed misleading messages

app/views/_accountSummary_sideBar.scala.html, app/views/accountSummary.scala.html, app/views/editLiability/editLiabilityDeclaration.scala.html, app/views/global_error_wrapper.scala.html, app/views/helpers/atedErrorSummary.scala.html, app/views/helpers/atedErrorWithBoundarySummary.scala.html, app/views/main.scala.html, app/views/printFriendly.scala.html, app/views/propertyDetails/propertyDetailsSummary.scala.html, app/views/reliefs/reliefsSummary.scala.html, app/views/reliefs/viewReliefReturn.scala.html, test/views/html/AccountSummarySpec.scala
DL-2890 - Accessability validation tool changes and tests
Small changes to hit the validation tool requirements. 
=> DL-2890 - Accessibility validation tool changes and tests

app/utils/AtedUtils.scala, app/utils/PeriodUtils.scala, app/views/editLiability/dataOfDisposal.scala.html, app/views/editLiability/disposeLiabilityBankDetails.scala.html, app/views/editLiability/disposeLiabilityHasBankDetails.scala.html, app/views/editLiability/editLiability.scala.html, app/views/editLiability/editLiabilitySummary.scala.html, app/views/helpers/atedInputRadioGroupNew.scala.html, app/views/propertyDetails/addressLookup.scala.html, app/views/propertyDetails/propertyDetailsAddress.scala.html, app/views/propertyDetails/propertyDetailsOwnedBefore.scala.html, app/views/propertyDetails/propertyDetailsRevalued.scala.html, app/views/propertyDetails/propertyDetailsSummary.scala.html, app/views/propertyDetails/propertyDetailsTitle.scala.html, test/controllers/LeaveFeedbackControllerSpec.scala, test/controllers/propertyDetails/PropertyDetailsProfessionallyValuedControllerSpec.scala, test/controllers/propertyDetails/PropertyDetailsTaxAvoidanceControllerSpec.scala, test/views/editLiability/disposeLiabilityBankDetailsSpec.scala, test/views/editLiability/disposeLiabilityHasBankDetailsSpec.scala, test/views/editLiability/editLiabilitySpec.scala, test/views/editLiability/editLiabilityValueSpec.scala, test/views/editLiability/hasBankDetailsSpec.scala, test/views/propertyDetails/PropertyDetailsRevaluedViewSpec.scala
=> DL-3309 - change views to be better support voice over screen reader

app/config/ErrorHandler.scala, app/controllers/auth/ClientHelper.scala, app/controllers/propertyDetails/ConfirmAddressController.scala, app/controllers/propertyDetails/PropertyDetailsDeclarationController.scala, app/controllers/propertyDetails/PropertyDetailsSupportingInfoController.scala, app/controllers/reliefs/ReliefDeclarationController.scala, app/controllers/subscriptionData/CorrespondenceAddressController.scala, app/views/global_error.scala.html, conf/messages, project/AppDependencies.scala, test/controllers/propertyDetails/ConfirmAddressControllerSpec.scala, test/controllers/subscriptionData/CorrespondenceAddressControllerSpec.scala
DL-3425: Generic error update 
New feature
Generic error update 
*Reviewee* (Nadin)
=> DL-3425: Generic error update 

app/connectors/AgentClientMandateFrontendConnector.scala, test/connectors/AgentClientMandateFrontendConnectorSpec.scala
**Bug fix**
* Removed logging for 404 statuses since they're expected functionality of ACM-FE when a mandate doesn't exist.
=> DL-2081 Removed logging for intended 404 behaviour

app/controllers/propertyDetails/PropertyDetailsSummaryController.scala, app/views/propertyDetails/propertyDetailsPrintFriendly.scala.html, project/AppDependencies.scala, project/plugins.sbt, test/controllers/propertyDetails/PropertyDetailsSummaryControllerSpec.scala
**Bug fix**
* Fixed exception when user attempts to print liability summary page with no details
=> DL-2911 Fixed exception on printing with incomplete details

build.sbt, conf/application-json-logger.xml, conf/logback.xml, project/AppDependencies.scala, project/plugins.sbt
DL-4174 Update logging config
Update
Update logging in xml files
=> DL-4174 Update logging config

conf/application.conf
DL-4213
**Accessibility**
Add entry to application.conf for accessibility
Version of play-ui already in place on master
=> DL-4213 implement ated accessibility statement

app/views/editLiability/dataOfDisposal.scala.html, app/views/editLiability/editLiabilityDatesLiable.scala.html, app/views/helpers/atedDateFieldsFree.scala.html, app/views/propertyDetails/periodDatesLiable.scala.html, app/views/propertyDetails/periodInReliefDates.scala.html, app/views/propertyDetails/propertyDetailsNewBuildDates.scala.html, app/views/propertyDetails/propertyDetailsRevalued.scala.html, app/views/propertyDetails/propertyDetailsWhenAcquired.scala.html, app/views/reliefs/chooseReliefs.scala.html, conf/application.conf, project/AppDependencies.scala, public/stylesheets/main.css
DL-4390
**Bug fix** 
Remove use of date-of-birth class for dates that do not relate to date-of-birth
Gone down the route outlined in the ticket and replaced date-of-birth with date
Amended helper atedDateFieldsFree - data-validation-name to use generic dateFields entry
updated main.css 
All tests remain unaffected and ATs run successfully
Manually checked pages that have changed for look and feel of the original
Updated dependencies and fix some warnings encountered when running slug
=> DL-4390 use generic groupclass and datavalidationame

build.sbt, conf/application.conf, project/AppDependencies.scala, project/plugins.sbt, public/stylesheets/bta.css
DL-4395
**Bug fix** (delete as appropriate)
Add css to bta.css file so that any messages (where present) has the same look as that in BTA
Updated dependencies
Removed sbt artifiactory as not required (handled within jenkins)
Updated deprecation warnings
=> DL-4395 fix bta message bubble css

app/views/editLiability/disposeLiabilityPrintFriendly.scala.html, app/views/editLiability/editLiabilityPrintFriendly.scala.html, app/views/editLiability/editLiabilitySummary.scala.html, app/views/propertyDetails/propertyDetailsPrintFriendly.scala.html, project/AppDependencies.scala
**Bug fix**
* Amended liability print pages to display in similar in regards to how the summary pages render.
=> DL-2906 Amend liability draft print details

test/views/editLiability/editLiabilityDeclarationSpec.scala
**Unit test**
* Included additional unit test that had similar coverage from ATs
=> DL-4517 Add additional unit test coverage from ATs

app/forms/ReliefForms.scala, test/controllers/reliefs/ReliefsSummaryControllerSpec.scala, test/forms/ReliefFormsSpec.scala, test/views/html/PrevPeriodsSummarySpec.scala
**Test changes**
* Added backlink tests where it was previously being covered in ATs before.
=> DL-3183 Added backlink tests for claim relief pages

test/controllers/propertyDetails/PropertyDetailsInReliefControllerSpec.scala, test/controllers/propertyDetails/PropertyDetailsProfessionallyValuedControllerSpec.scala
**Unit test coverage**
* Improved unit test coverage to cover removed tests from acceptance tests.
=> DL-3185 Unit test coverage for chargeable return

project/AppDependencies.scala, test/controllers/subscriptionData/CompanyDetailsControllerSpec.scala, test/controllers/subscriptionData/EditContactDetailsControllerSpec.scala, test/controllers/subscriptionData/EditContactEmailControllerSpec.scala
**Test upgrades**
* Added additional unit test coverage that was previously covered by ATs
=> DL-3189 Added unit test coverage from ATs

app/config/ApplicationConfig.scala, app/controllers/auth/AuthAction.scala, conf/application.conf, project/AppDependencies.scala, test/controllers/auth/AuthActionSpec.scala, test/controllers/auth/ExternalUrlsSpec.scala
**Dependency update**
* Replaced CA_FRONTEND dependency with bas-gateway-frontend
=> DL-4813 Remove CA_FRONTEND dependency

test/controllers/propertyDetails/PropertyDetailsTitleControllerSpec.scala, test/forms/PropertyDetailsFormsSpec.scala
DL-3194 Add unit test coverage for form validation
**Unit tests**
* Added unit test coverage for form validation that was previously tested in ATs
=> DL-3194 Add unit test coverage for form validation

app/config/ApplicationConfig.scala, app/views/global_error_wrapper.scala.html, app/views/helpers/ga.scala.html, app/views/main.scala.html, conf/application.conf
GTMRevert added ga.scala back to repo
Reverting GTM changes so they don't block the pipeline
*Reviewee* (Iyke)
=> GTMRevert added ga.scala back to repo

test/controllers/reliefs/ViewReliefReturnControllerSpec.scala
**Unit test**
Added a back link test for view relief page.
=> DL-3196 Added back link test for view relief page

test/views/reliefs/avoidanceSchemes.scala
=> DL-3195 Add unit test for avoidance scheme details page

build.sbt, it/controllers/reliefs/ReliefDeclarationControllerISpec.scala, it/helpers/IntegrationBase.scala, it/helpers/IntegrationConstants.scala, it/helpers/application/IntegrationApplication.scala, it/helpers/stubs/AuthAudit.scala, it/helpers/stubs/GGLoginStub.scala, it/helpers/stubs/KeyStore.scala, it/helpers/wiremock/WireMockConfig.scala, it/helpers/wiremock/WireMockSetup.scala, project/AppDependencies.scala, project/TestPhases.scala
ATED: Cooperative Housing - Create Integration Tests
An integration test for submitting a relief is running and passing
*Reviewee* (Iyke, Marjan)
=> DL-4928 Submit Relief Integration Test

app/views/accountSummary.scala.html, app/views/helpers/coopHousing.scala.html, app/views/helpers/noReturnsText.scala.html, app/views/helpers/peakGuidance.scala.html, conf/messages, test/views/html/helpers/peakGuidanceSpec.scala
=> DL-4873 - Add social housing info to summary page.

conf/application.conf
Coop Housing Feature Switch
Switched on Coop Housing changes
*Reviewee* (Iyke)
=> Coop Housing Feature Switch

public/stylesheets/main.css
**Bug fix**
* Fixed missing hidden disclosure arrows on ated-frontend
=> DL-5361 Fixed hidden disclosure arrow

README.md, build.sbt, project/plugins.sbt
=> DL-5402: Bintray update

project/AppDependencies.scala, project/plugins.sbt
DL-6850
**Mainetnance**
Adding scope to Test dependencies
Upgrade other plugins to latest
*Reviewee* (Paul Anderson)
=> DL-6850 apply missing test config in dependencies plus plugin updates

app/views/AttorneyRegime.scala, app/views/ViewUtils.scala, app/views/atttorneyBanner.scala.html, app/views/formBundleReturn.scala.html, app/views/layout.scala.html, app/views/newMain.scala.html, app/views/returnType.scala.html, conf/application.conf, conf/messages, test/controllers/ReturnTypeControllerSpec.scala, test/views/html/ReturnTypeSpec.scala
PR for acceptance tests: https://github.com/hmrc/ated-acceptance-tests/pull/116
=> DL-7004: layout/main fixes and returType migrated

conf/app.routes
**Bug fix** 
Fixing issue identified in routes file which was incorrectly syntaxed
*Reviewee* (Paul Anderson)
=> VRCrouteFix applying correct path for view relief return

app/views/subcriptionData/companyDetails.scala.html, project/AppDependencies.scala
DL-7993
**Bug fix** 
Update companyDetails view to reflect the correct detail for email address
*Reviewee* (Paul Anderson)
=> DL-7993 update display to show email address

app/views/editLiability/disposeLiabilityPrintFriendly.scala.html, app/views/editLiability/disposeLiabilitySummary.scala.html, conf/messages, project/AppDependencies.scala, test/controllers/editLiability/DisposeLiabilitySummaryControllerSpec.scala, test/views/editLiability/disposeLiabilitySummarySpec.scala
Added more bank details to dispose summary, added unit tests
=> DL-8658: Added more bank details to dispose summary

app/controllers/editLiability/BankDetailsController.scala, app/views/editLiability/editLiabilityPrintFriendly.scala.html, app/views/editLiability/editLiabilitySummary.scala.html, app/views/propertyDetails/propertyDetailsPrintFriendly.scala.html, conf/app.routes, test/builders/PropertyDetailsBuilder.scala, test/views/editLiability/editLiabilitySummarySpec.scala
DL-8659: Added more bank details to change summary
=> DL-8659: Added more bank details to change summary

app/views/helpers/periodSummaryPastTabHelper.scala.html
DL-7411: Removed drafts from past returns tab
=> DL-7411: Removed drafts from past returns tab

project/AppDependencies.scala, project/plugins.sbt
Udate play-frontend-hmrc to latest version
Fix scalastyle warns relating to mismatched header
Update other dependencies
=> DL-9486 update play fromtend hmrc to latest and fix scalastyle warns

app/forms/AtedForms.scala, app/forms/PropertyDetailsForms.scala, app/forms/ReliefForms.scala, app/forms/mappings/DateTupleCustomError.scala, conf/messages
DL-6457: Fixed Choose relief view dates
=> DL-6457: Fixed Choose relief view dates

app/controllers/editLiability/DisposePropertyController.scala, app/controllers/propertyDetails/PropertyDetailsRevaluedController.scala, app/forms/AtedForms.scala, app/forms/mappings/DateTupleCustomError.scala, conf/messages, test/controllers/editLiability/DisposePropertyControllerSpec.scala
DL-10800 DisposePropertyController GDS dates adaptation
Bug Fix
=> DL-10800 DisposePropertyController GDS dates adaptation

app/controllers/editLiability/EditLiabilityDatesLiableController.scala, app/controllers/propertyDetails/IsFullTaxPeriodController.scala, app/controllers/propertyDetails/PeriodDatesLiableController.scala, app/forms/PropertyDetailsForms.scala, app/forms/PropertyDetailsFormsValidation.scala, app/models/PropertyDetailsModels.scala, conf/messages, test/connectors/PropertyDetailsConnectorSpec.scala, test/controllers/editLiability/EditLiabilityDatesLiableControllerSpec.scala, test/forms/PeriodDatesLiableFormSpec.scala, test/forms/PropertyFormValidationSpec.scala, test/services/PropertyDetailsServiceSpec_Periods.scala
DL-11595 EditLiabilityDatesLiableController GDS Compliant changes for dates
Mohan Dolla
=> DL-11595 EditLiabilityDatesLiableController GDS Compliant changes for dates

app/views/editLiability/disposeLiabilityPrintFriendly.scala.html, app/views/editLiability/disposeLiabilitySentPrintFriendly.scala.html, app/views/editLiability/editLiabilityPrintFriendly.scala.html, app/views/editLiability/editLiabilitySentPrintFriendly.scala.html, app/views/layout.scala.html, app/views/propertyDetails/chargeableConfirmationPrintFriendly.scala.html, app/views/propertyDetails/propertyDetailsPrintFriendly.scala.html, app/views/propertyDetails/propertyDetailsRevalued.scala.html, app/views/reliefs/invalidPeriodKey.scala.html, app/views/reliefs/reliefsSent.scala.html, app/views/reliefs/reliefsSummary.scala.html, app/views/subcriptionData/correspondenceAddress.scala.html, app/views/subcriptionData/overseasCompanyRegistration.scala.html, app/views/subcriptionData/registeredDetails.scala.html, conf/application.conf, test/controllers/reliefs/ReliefsSummaryControllerSpec.scala, test/views/reliefs/ReliefsSentSpec.scala
CSP config update
Updated scripts to use CSP attr helper
Note - no changes applied to compilation WARNs or dependency updates as these are being handled under separate 2.13 upgrade ticket
app-config-* updates:
https://github.com/hmrc/app-config-staging/pull/13929
https://github.com/hmrc/app-config-qa/pull/20227
https://github.com/hmrc/app-config-production/pull/19969
=> DL-11516 CSP config update

app/assets/stylesheets/application.scss
=> Increase spacing between grey buttons to improve accessibility

app/views/formBundleReturn.scala.html, app/views/reliefs/viewReliefReturn.scala.html
=> update unsemantic divs to paragraphs

app/assets/stylesheets/bta.css, app/views/service_info.scala.html
Addressing issue with Accessibility report relating to 'Ensures landmarks are unique'
Discussed and addressed with FE developer
Remove inline styling and place in css file
Add aria-labelledBy attribute to address navigation issue
Checked manually using screen reader 0 to appear on navigation menu
Manual axe check of page to ensure issue resolved
=> DL-13296 address landmarks unique accessibilty issue with BTA menu

app/views/reliefs/avoidanceSchemes.scala.html, test/controllers/reliefs/AvoidanceSchemesControllerSpec.scala, test/views/reliefs/AvoidanceSchemesSocialHousingSpec.scala, test/views/reliefs/avoidanceSchemesSpec.scala
Amending avoidance scheme and promoter reference fields to make them more accessible
=> DL-13506: removed maxLength attribute and enhanced tests

app/controllers/propertyDetails/PropertyDetailsDateOfRevalueController.scala, app/forms/PropertyDetailsForms.scala, app/models/PropertyDetailsModels.scala, app/views/propertyDetails/propertyDetailsDateOfRevalue.scala.html, conf/app.routes, conf/messages, test/views/propertyDetails/PropertyDetailsDateOfRevalueSpec.scala
=> DL-13363 - Date of revaluepage

app/controllers/propertyDetails/PropertyDetailsNewValuationController.scala, app/utils/AtedConstants.scala, app/views/propertyDetails/propertyDetailsNewValuation.scala.html, test/controllers/propertyDetails/PropertyDetailsNewValuationControllerSpec.scala
=> DL-13376: Added controller for new valuation page

app/controllers/propertyDetails/PropertyDetailsDateOfChangeController.scala, app/utils/AtedConstants.scala, conf/application.conf, test/controllers/propertyDetails/PropertyDetailsDateOfChangeControllerSpec.scala
DL-13373
completed the date of change controller
Berna
=> DL-13373: £40,000 change date controller

app/controllers/propertyDetails/PropertyDetailsDateOfRevalueController.scala, app/utils/AtedConstants.scala, test/controllers/propertyDetails/PropertyDetailsDateOfRevalueControllerSpec.scala
New feature
Edited the controller for the date of revalue page. Tests added for controller.
Berna
=> DL-13378: date of revalue controller

app/controllers/propertyDetails/PropertyDetailsDateOfChangeController.scala, app/controllers/propertyDetails/PropertyDetailsDateOfRevalueController.scala, app/controllers/propertyDetails/PropertyDetailsHasBeenRevaluedController.scala, app/controllers/propertyDetails/PropertyDetailsNewValuationController.scala
=> DL-13368 : wiring up task and fixing backlink cache

app/forms/PropertyDetailsForms.scala, app/models/PropertyDetailsModels.scala, app/utils/AtedUtils.scala, app/views/propertyDetails/addressLookup.scala.html, app/views/propertyDetails/propertyDetailsAddress.scala.html, app/views/subcriptionData/correspondenceAddress.scala.html, build.sbt, project/AppDependencies.scala, project/plugins.sbt, test/views/propertyDetails/propertyDetailsNewValuationSpec.scala
**New feature**
Enables autocomplete and inputmode attributes for few input fields
*Reviewee* (Preetam)
=> feat(DL-14866): Enable autocomplete and inputmode attributes

app/connectors/PropertyDetailsConnector.scala, app/controllers/propertyDetails/PropertyDetailsTaxAvoidanceReferencesController.scala, app/controllers/test/PropertyDetailsTaxAvoidanceReferencesController.scala, app/forms/PropertyDetailsForms.scala, app/forms/PropertyDetailsFormsValidation.scala, app/models/PropertyDetailsModels.scala, app/services/PropertyDetailsService.scala, app/views/propertyDetails/propertyDetailsTaxAvoidanceReferences.scala.html, conf/app.routes, conf/messages, conf/testOnlyDoNotUseInAppConf.routes, test/controllers/propertyDetails/PropertyDetailsTaxAvoidanceReferencesControllerSpec .scala, test/views/html/propertyDetails/PropertyDetailsTaxAvoidanceReferenceSpec.scala
=> DL-14939: Enter your avoidance scheme details Page

app/connectors/PropertyDetailsConnector.scala, app/controllers/test/PropertyDetailsTaxAvoidanceSchemeController.scala, app/forms/PropertyDetailsForms.scala, app/models/PropertyDetailsModels.scala, app/services/PropertyDetailsService.scala, app/views/propertyDetails/propertyDetailsTaxAvoidanceScheme.scala.html, conf/messages, conf/testOnlyDoNotUseInAppConf.routes, test/controllers/propertyDetails/PropertyDetailsTaxAvoidanceSchemeControllerSpec.scala, test/views/html/propertyDetails/PropertyDetailsTaxAvoidanceSchemeHtmlViewSpec.scala
=> DL-14935, TaxAvoidance Scheme page Changes

build.sbt, project/AppDependencies.scala, project/plugins.sbt
=> DL-15456 : Updated libraries

test/controllers/SelectPeriodControllerSpec.scala
=> DL-15761, Updated ated chargeable periods to fix test case

project/AppDependencies.scala, project/plugins.sbt
=> DL-15631 - Updates dependencies

conf/application.conf, project/build.properties, test/controllers/SelectPeriodControllerSpec.scala
=> DL-15636 remove unused conf

app/config/ApplicationConfig.scala, app/controllers/ApplicationController.scala
=> Fixing signout url

app/views/propertyDetails/propertyDetailsNewBuild.scala.html, conf/messages, test/views/propertyDetails/propertyDetailsNewBuildSpec.scala
=> DL-15167: Updated is new property page
