app/controllers/auth/AuthAction.scala, test/controllers/ExistingReturnQuestionControllerSpec.scala, test/controllers/PeriodSummaryControllerSpec.scala, test/controllers/auth/AuthActionSpec.scala, test/controllers/propertyDetails/AddressLookupControllerSpec.scala, test/controllers/propertyDetails/IsFullTaxPeriodControllerSpec.scala, test/controllers/propertyDetails/PeriodChooseReliefsControllerSpec.scala, test/controllers/propertyDetails/PeriodDatesLiableControllerSpec.scala, test/controllers/propertyDetails/PropertyDetailsAddressControllerSpec.scala, test/controllers/propertyDetails/PropertyDetailsDeclarationControllerSpec.scala, test/controllers/propertyDetails/PropertyDetailsInReliefControllerSpec.scala, test/controllers/propertyDetails/PropertyDetailsOwnedBeforeControllerSpec.scala, test/controllers/propertyDetails/PropertyDetailsSupportingInfoControllerSpec.scala, test/controllers/propertyDetails/PropertyDetailsTaxAvoidanceControllerSpec.scala, test/utils/MockAuthUtil.scala
DL-2269b - refactor to address gateway redirect issue identified in QA
**Bug fix** (delete as appropriate)
Refactoring Auth and AuthSpec to rectify behaviour on new Auth which did not reflect the current behaviour prior to the upgrade. Rerouting to Gateway login now occurs for NoActiveSession.
=> DL-2269b refactor to fix GG routing issue plus tidy

app/services/ReliefsService.scala, test/services/ReliefsServiceSpec.scala
DL-2390
**Bug fix** 
Internal error being thrown back through the frontend where back end returns not found for RetrieveDraftReliefs. 
=> DL-2390 address issue with error being thrown for Not Found

app/controllers/reliefs/ChooseReliefsController.scala, app/utils/ReliefsUtils.scala, project/plugins.sbt, test/controllers/reliefs/ChooseReliefsControllerSpec.scala, test/utils/ReliefsUtilsSpec.scala
DL-2435 Fixed invalid dates on unused reliefs being validated
**Bug fix**
* Fixed invalid dates pertaining to unselected reliefs on the choose reliefs page causing the page to be unable to submit.
=> DL-2435 Fixed invalid dates on unused reliefs being validated

app/controllers/propertyDetails/PropertyDetailsDeclarationController.scala, test/controllers/propertyDetails/PropertyDetailsDeclarationControllerSpec.scala
**Bug fix**
* Prevented being able to access the declaration page in invalid scenarios.
=> DL-2607 Prevent tampering to access declaration URL

app/views/periodSummary.scala.html, test/views/periodSummarySpec.scala
**Bug fix**
The only functional change is a simple content change on period-summary. **View** now says **View or change**
*Reviewee* (Chris)
=> DL-2499 Changed 'view' to 'view or change' on period-summary

project/plugins.sbt
DepUpdate
Reduce version sbt-auto-build due to errors in IntelliJ when building with version 2.4.0. Upgraded sbt plugin for sbt coverage to version 1.6.1.
=> sbt auto build version 230 and increment sbt coverage version

app/controllers/propertyDetails/SelectExistingReturnAddressController.scala, app/models/AddressLookupModels.scala, app/services/SummaryReturnsService.scala, test/controllers/ReturnTypeControllerSpec.scala, test/controllers/propertyDetails/SelectExistingReturnAddressControllerSpec.scala, test/services/SummaryReturnsServiceSpec.scala
DL-2592 Added logic for unique addresses
**Bug fix** 
On the "/existing-return/select/2017/charge" page duplicate properties were shown because they were being pulled from both the current return and past return section. This bug fix allows for only the latest property to be pulled thereby removing duplicate properties on the page.
Iyke
=> DL-2592 Added logic for unique addresses

app/views/global_error.scala.html
**Bug fix**
Bug caused by play 2.6 upgrade, missing 'messages' tag to convert key into actual content.
*Reviewee* (Dan)
*Reviewer* Iyke
=> DL-2670: Title key error fix

app/config/ApplicationConfig.scala, app/controllers/ApplicationController.scala, app/views/error/individual.scala.html, app/views/unauthorised.scala.html, conf/app.routes, conf/application.conf, conf/messages, test/controllers/ApplicationControllerSpec.scala
**Maintenance** 
Added new unauthorised view for individuals trying to access ATED. The link URLs are in config so that changing without a redeployment is an option.
*Reviewee* (Chris)
*Reviewer* (Iyke)
=> DL-2333 Amended content for individual auth failure

app/controllers/propertyDetails/IsFullTaxPeriodController.scala, app/services/PropertyDetailsService.scala, app/views/editLiability/editLiabilityPrintFriendly.scala.html, app/views/propertyDetails/propertyDetailsSummary.scala.html, conf/messages, project/FrontendBuild.scala, project/plugins.sbt, test/controllers/propertyDetails/IsFullTaxPeriodControllerSpec.scala
**Bug fix** 
Users have been seeing system errors when submitting the supporting information for their return. This is because a backend return calculation is triggered on the post of supporting info, even if the user has not provided all of the information required for that calculation to complete successfully. 
To resolve this issue, the user needs to see every page required for their journey, so they have the opportunity to answer the questions required for the calculation. 
The changes of this PR are as follows:-
- ensure the user is able to access the full-tax-period question which the user is currently being diverted away from so are unable to complete all required questions
- take the user to the **Has the value of your property changed for the purposes of ATED?** page from the …
=> DL-2240: Resolve corrupt return state issues

app/controllers/propertyDetails/AddressLookupController.scala, app/controllers/propertyDetails/ConfirmAddressController.scala, app/controllers/propertyDetails/PropertyDetailsAddressController.scala, app/controllers/propertyDetails/SelectExistingReturnAddressController.scala, app/views/confirmPastReturn.scala.html, app/views/helpers/pageHeadersAndError.scala.html, app/views/propertyDetails/confirmAddress.scala.html, app/views/propertyDetails/propertyDetailsAddress.scala.html, app/views/propertyDetails/selectPreviousReturn.scala.html, conf/app.routes, conf/messages, scalastyle-config.xml, test/controllers/ExistingReturnQuestionControllerSpec.scala, test/controllers/propertyDetails/ConfirmAddressControllerSpec.scala, test/controllers/propertyDetails/SelectExistingReturnAddressControllerSpec.scala
Select previous address - guide user to select continuity of record correctly
"Yes" flow for "/ated/existing-return/confirmation/2017/charge"
*Iyke* 
=> DL-2502 Select previous address flow change

app/config/ApplicationConfig.scala, app/controllers/AccountSummaryController.scala, app/services/DateService.scala, app/views/accountSummary.scala.html, app/views/atedMain.scala.html, app/views/helpers/peakGuidance.scala.html, app/views/helpers/warning.scala.html, app/views/main.scala.html, conf/application.conf, conf/messages, project/plugins.sbt, test/controllers/AccountSummaryControllerSpec.scala, test/services/DateServiceSpec.scala, test/views/html/helpers/peakGuidanceSpec.scala
**REMEMBER app-config-production change
https://github.com/hmrc/app-config-production/pull/5868**
This story adds some content to the top of ated home which reminds users about their return deadlines. There is dynamic content depending on whether we are in or out of the ated peak period of xx March to 30th April. The day is configurable so we can set when this content is displayed each year.
*David Thornton* (Reviewee)
=> DL-2766: Added configurable peak and non-peak content to ated home

app/controllers/AccountSummaryController.scala, app/views/accountSummary.scala.html, app/views/helpers/peakGuidance.scala.html, conf/messages, test/views/html/helpers/peakGuidanceSpec.scala
Corrected logic to ensure the correct years are displayed on account summary when out of ATED peak. Before the years were based on current year and are now based on current tax year.
*Reviewee* (David Thornton)
=> DL-2766: Updated logic on for ATED configurable deadline content

app/views/reliefs/changeReliefReturn.scala.html
DL-2763-b swapped paragraphs around
**Before**
**After**
Iyke
=> DL-2763-b swapped paragraphs around

app/views/helpers/pageHeadersAndError.scala.html, test/views/editLiability/editLiabilitySpec.scala, test/views/editLiability/editLiabilitySummarySpec.scala, test/views/formBundleReturnSpec.scala, test/views/periodSummaryPastReturnsSpec.scala, test/views/periodSummarySpec.scala, test/views/propertyDetails/PropertyDetailsAddressSpec.scala, test/views/propertyDetails/PropertyDetailsRevaluedViewSpec.scala, test/views/propertyDetails/addressLookupResultsSpec.scala, test/views/propertyDetails/addressLookupSpec.scala, test/views/propertyDetails/periodChooseReliefSpec.scala, test/views/propertyDetails/periodDatesLiableSpec.scala, test/views/propertyDetails/periodsInAndOutReliefSpec.scala, test/views/propertyDetails/propertyDetailsTitleSpec.scala, test/views/reliefs/ReliefDeclarationSpec.scala, test/views/reliefs/changeReliefReturnSpec.scala, test/views/reliefs/chooseReliefsSpec.scala, test/views/reliefs/isAvoidanceSchemeSpec.scala
amend pageHeadersAndError to only display backlink where defined
**Bug fix** 
Updated pageHeadersAndError to not display the back link on views where it was not defined or defined as None in relevant view.
Fixing tests which where previously setting backlink as None and verifying that it existed on page
=> BackLinkChanges 

app/controllers/AccountSummaryController.scala, app/controllers/SelectPeriodController.scala, app/models/summaryReturnsModels.scala, app/services/ReliefsService.scala, app/services/SummaryReturnsService.scala, app/utils/AtedConstants.scala, app/views/_accountSummary_sideBar.scala.html, app/views/accountSummary.scala.html, app/views/atedMain.scala.html, app/views/atedNoAuthMain.scala.html, app/views/helpers/accountSummaryRow.scala.html, conf/messages, project/FrontendBuild.scala, project/plugins.sbt, public/stylesheets/_checkAnswers.css, public/stylesheets/main.css, test/controllers/AccountSummaryControllerSpec.scala, test/controllers/SelectPeriodControllerSpec.scala, test/controllers/editLiability/DisposeLiabilitySentControllerSpec.scala, test/controllers/propertyDetails/ChargeableReturnConfirmationControllerSpec.scala, test/models/SummaryReturnsModelSpec.scala, test/services/SummaryReturnsServiceSpec.scala, test/utils/TestModels.scala, test/views/html/AccountSummarySidebarSpec.scala, test/views/html/AccountSummarySpec.scala, test/views/html/helpers/formattedPoundsSpec.scala, test/views/html/subscriptionData/CompanyDetailsSpec.scala
**New feature**
See story
*Reviewee* (David Thornton)
=> DL-2769: Split current returns into a definition list on account summary

app/controllers/PeriodSummaryController.scala, app/controllers/reliefs/ViewReliefReturnController.scala, app/services/ReliefsService.scala, app/services/SummaryReturnsService.scala, app/utils/ReliefsUtils.scala, app/views/periodSummary.scala.html, app/views/periodSummaryPastReturns.scala.html, app/views/reliefs/viewReliefReturn.scala.html, test/controllers/PeriodSummaryControllerSpec.scala, test/controllers/reliefs/ViewReliefReturnControllerSpec.scala, test/services/ReliefsServiceSpec.scala, test/services/SummaryReturnsServiceSpec.scala, test/utils/ReliefsUtilsSpec.scala, test/views/periodSummaryPastReturnsSpec.scala, test/views/periodSummarySpec.scala
**Bug fix**
* Submitted repeated relief codes, if the relief is a day or older, no longer appear twice on the current returns tab - they have now been moved to the
=> DL-2623 Repeated relief codes in current returns

app/views/atedMain.scala.html, app/views/atedNoAuthMain.scala.html, app/views/error/individual.scala.html, app/views/propertyDetails/confirmAddress.scala.html, app/views/propertyDetails/periodsInAndOutRelief.scala.html, conf/messages, public/stylesheets/focus.css, public/stylesheets/main.css, public/stylesheets/palette.css, public/stylesheets/urBanner.css
DL-2384: Added css files to correct colour contrasts for WCAG 2.1
Added palette and focus css files as recommended at the time the accessibility statements were being rolled out to address any colour or focus accessibility issues. 
=> DL-2384: Added css files to correct colour contrasts for WCAG 2.1

public/stylesheets/focus.css
Elements with the .button class were not showing the black underline due to a css mistake.
=> Corrected button focus css

app/controllers/reliefs/ReliefDeclarationController.scala, app/models/SubmitReturnsResponse.scala, app/services/ReliefsService.scala, app/utils/AtedConstants.scala, conf/messages, test/controllers/reliefs/ReliefDeclarationControllerSpec.scala, test/services/ReliefsServiceSpec.scala
DL-3360 Catch NOT FOUND when submitting reliefs
**Bug fix**
Code to catch different status responses when submitting a draft relief. This should help fix the bug displayed in DL-2690
*Iyke*
=> DL-3360 Catch NOT FOUND when submitting reliefs

app/controllers/propertyDetails/PropertyDetailsSupportingInfoController.scala, app/models/SubmitReturnsResponse.scala, app/services/PropertyDetailsService.scala, app/views/propertyDetails/propertyDetailsSummary.scala.html, project/AppDependencies.scala, test/builders/PropertyDetailsBuilder.scala, test/controllers/propertyDetails/PropertyDetailsSupportingInfoControllerSpec.scala, test/services/PropertyDetailsServiceSpec.scala
**Bug fix**
* Changes the way the calculation is handled to only redirect to the summary on a no content with the corrosponding backend change
=> DL-3236 Redirect to summary on no content instead of any non-ok status

app/services/SubscriptionDataAdapterService.scala, test/services/SubscriptionDataAdapterServiceSpec.scala
**Bug fix**
* Editing the email address of an ATED subscription now no longer sends both address blocks, as this is invalid in the API schema.
=> DL-3295 Only send one address block for editing email

test/builders/SessionBuilder.scala, test/controllers/ControllerBaseSpec.scala
**Bug fix**
* Removed deprecated references to SessionKeys in ated-frontend
=> DL-4121 Removed SessionKeys references

app/controllers/BackLinkController.scala, app/controllers/editLiability/EditLiabilityTypeController.scala, test/builders/SessionBuilder.scala, test/controllers/editLiability/EditLiabilityTypeControllerSpec.scala
DL-4515: Added pre-population to edit return type page
=> DL-4515: Added pre-population to edit return type page

project/AppDependencies.scala, project/plugins.sbt, test/controllers/propertyDetails/PropertyDetailsAddressControllerSpec.scala, test/controllers/propertyDetails/PropertyDetailsSummaryControllerSpec.scala
Unit Test coverage for Chargeable Property Declare Page
**New feature**
No changes made to PropertyDetailsAddressControllerSpec because the cache is already being tested.
Added tests into PropertyDetailsSummaryControllerSpec to test the edit links.
This allowed me to delete several lines of tests from the ated acceptance tests.
*Iyke* 
=> DL-3182 Moved acceptance tests to unit tests

test/controllers/editLiability/EditLiabilityDatesLiableControllerSpec.scala, test/controllers/propertyDetails/PropertyDetailsSupportingInfoControllerSpec.scala, test/forms/PeriodDatesLiableFormSpec.scala
DL-3191
**Maintenance** 
Adding tests to cover some error validation that was being done in ATs repo (largely for Further Returns feature)
Included tests for error message key validation in PeriodDatesLiableFormSpec as it shared similar error messages and was missing these error validations
Added check for existence of supportingInfo_chars on Supporting Info view
=> DL-3191 adding error validation checks

test/controllers/subscriptionData/CorrespondenceAddressControllerSpec.scala
DL-3190
**Maintenance** 
Adding additional test to check for validation message where UK country has been selected but no postcode added
=> DL-3190 adding test for Correspondence address validation

app/controllers/propertyDetails/SelectExistingReturnAddressController.scala, app/models/AddressLookupModels.scala, app/services/SummaryReturnsService.scala, test/controllers/ReturnTypeControllerSpec.scala, test/controllers/propertyDetails/SelectExistingReturnAddressControllerSpec.scala, test/services/SummaryReturnsServiceSpec.scala, test/utils/TestModels.scala
**Bug fix**
* Fixes an issue where the incorrect property value could be selected by choosing a too old form bundle reference number that was uneditable.
=> DL-3725 Incorrect property value fix

conf/messages
DL-5505 ATED Accessibility: Non-descriptive links 1 
test pass without any update
Link content updated to provide more context to fix accessibility A WCAG 2.1 fail.
=>  DL-5505 Updating link content to improve accessibility

conf/country-code.properties
Sanitised properties file that was prepending hidden character to start of file.
=> DL-6759: Removed BOM from country-code.properties

app/views/prevPeriodsSummary.scala.html, conf/messages
This additional content, presumably designed to improve the accessibility of the table, actually made it more confusing to navigate. Removing it and adding a visually hidden caption has vastly improved this for screen reader users.
Unused message keys removed.
Unit test ran and unaffected.
=> Remove unnecessary visually hidden content from table

app/services/FormBundleReturnsService.scala, test/services/FormBundleReturnsServiceSpec.scala
**Bug fix**
Attempted fix for dealing with illegal unquoted characters in the json for the form bundle.
=> DL-13817 Dealing with illegal unquoted character in form bundle

test/ProductionAndTestRoutesSpec.scala
New feature
added unit tests to ensure that test routes stay in their assigned file and aren't accidentally put into production via the app.routes file or the application.conf file. Tests also fail if test routes are not prefixed correctly.
=> DL-14934: Implementation to ensure new routing is not pushed to live
